### ISSUE TITLE
"Download Page" link on docs/app_demo.md incorrect

### ISSUE THREAD

**Issue by svenlowrybjss** [SasaKaranovic/VU-Documentation#1]
The "Download Page" link on `docs/app_demo.md` currently links to the GitHub repo - the same as the "Source Code" link next to it.
Looks like it should be pointing at https://vudials.com/download/demo_app instead

**Comment by SasaKaranovic** [comment]
Thanks @svenlowrybjss !

The "public" download link for the demo application was not available at the time of writing the documentation. Thank you for bringing this up. The updated version is now live.
